name: CI
on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install app deps
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Import checks
        run: |
          python - <<'PY'
          # Minimal smoke test: just import the libs your app needs
          import gradio
          from fastai.vision.all import load_learner
          print("Imports OK")
          PY
